const express=require('express'),cors=require('cors'),crypto=require('crypto'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),multer=require('multer'),mongoose=require('mongoose');
require('dotenv').config({ path: require('path').join(__dirname, '.env') }); const cloudinary=require('cloudinary').v2; const Lead=require('./MODELS/Lead'),Team=require('./MODELS/Team');
const OfferSetting=require('./MODELS/OfferSetting'); const app=express(),PORT=Number(process.env.PORT||5000),FRONTEND_ORIGIN=process.env.FRONTEND_ORIGIN||'http://localhost:5173',JWT_SECRET=process.env.JWT_SECRET||'';
app.disable('x-powered-by');app.set('trust proxy',1);app.use(cors({origin:FRONTEND_ORIGIN.split(',').map(s=>s.trim()),methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:false,limit:'100kb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','same-site');if(req.secure||req.headers['x-forwarded-proto']==='https')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next()});
const buckets=new Map();function rateLimit({windowMs=60000,max=60,keyFn=req=>req.ip}={}){return(req,res,next)=>{const now=Date.now(),key=keyFn(req);let b=buckets.get(key);if(!b||now-b.start>=windowMs)b={start:now,count:0},buckets.set(key,b);if(++b.count>max){res.setHeader('Retry-After',Math.ceil((b.start+windowMs-now)/1000));return res.status(429).json({success:false,message:'Too many requests. Please try again later.'})}next()}}
app.use('/api',rateLimit({max:120}));const loginLimiter=rateLimit({windowMs:600000,max:8,keyFn:r=>`login:${r.ip}`}),leadLimiter=rateLimit({windowMs:600000,max:12,keyFn:r=>`lead:${r.ip}`});
cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(['image/jpeg','image/png','image/webp'].includes(f.mimetype)?null:new Error('Only JPG, PNG and WEBP images are allowed.'))});
const text=(v,m=500)=>typeof v==='string'?v.trim().slice(0,m):'',validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'')),validUrl=v=>{if(!v)return '';try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}},validId=v=>mongoose.isValidObjectId(v);
function auth(req,res,next){const h=req.get('authorization')||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,message:'Unauthorized access.'});try{const d=jwt.verify(h.slice(7),JWT_SECRET,{issuer:'growtechaxon-api',audience:'growtechaxon-admin'});if(d.role!=='admin')throw 0;req.admin=d;next()}catch{return res.status(401).json({success:false,message:'Invalid or expired token.'})}}
function uploadCloud(buffer){return new Promise((resolve,reject)=>cloudinary.uploader.upload_stream({folder:'growtechaxon/team',resource_type:'image'},(e,r)=>e?reject(e):resolve(r)).end(buffer))}
app.get('/',(r,s)=>s.json({success:true,service:'GrowtechAxon API',status:'running',api:'/api',health:'/api/health'}));
app.get('/api',(r,s)=>s.json({success:true,service:'GrowtechAxon API',status:'running',health:'/api/health',message:'API server is running. Use /api/* routes.'}));

async function getOfferSettings(){ let settings=await OfferSetting.findOne({key:'public-offer'}); if(!settings) settings=await OfferSetting.create({key:'public-offer'}); return settings; }
app.get('/api/offer-settings',async(req,res)=>{try{const x=await getOfferSettings();res.set('Cache-Control','no-store');res.json({success:true,offer:{enabled:x.enabled,title:x.title,description:x.description,durationDays:x.durationDays,maxClients:x.maxClients,terms:x.terms}})}catch(e){res.status(503).json({success:false,message:'Offer settings temporarily unavailable.'})}});
app.put('/api/admin/offer-settings',auth,async(req,res)=>{try{const d={enabled:req.body.enabled===true,title:text(req.body.title,120)||'Get Your Website for Free!',description:text(req.body.description,500),durationDays:Math.max(1,Math.min(365,Number(req.body.durationDays)||30)),maxClients:Math.max(1,Math.min(10000,Number(req.body.maxClients)||10)),terms:text(req.body.terms,5000)};const x=await OfferSetting.findOneAndUpdate({key:'public-offer'},{$set:d,$setOnInsert:{key:'public-offer'}},{new:true,upsert:true,runValidators:true});res.json({success:true,message:'Offer settings saved.',offer:x})}catch(e){res.status(500).json({success:false,message:'Unable to save offer settings.'})}});

app.get('/api/health',(r,s)=>s.json({success:true,status:'ok',service:'GrowtechAxon API',time:new Date().toISOString()}));
app.get('/api/test',(r,s)=>s.json({success:true,message:'GrowtechAxon API is working.'}));
app.post('/api/admin/login',loginLimiter,async(req,res)=>{try{const u=text(req.body.username,80),p=String(req.body.password||'');if(!u||!p)return res.status(400).json({success:false,message:'Username and password are required.'});const expected=String(process.env.ADMIN_USERNAME||'');const passwordHash=String(process.env.ADMIN_PASSWORD_HASH||'');const plainPassword=String(process.env.ADMIN_PASSWORD||'');if(JWT_SECRET.length<32||!expected||(!passwordHash&&!plainPassword))return res.status(503).json({success:false,message:'Authentication is not configured securely.'});const userOk=u===expected,passOk=passwordHash?await bcrypt.compare(p,passwordHash):p===plainPassword;if(!userOk||!passOk)return res.status(401).json({success:false,message:'Invalid username or password.'});const token=jwt.sign({username:u,role:'admin'},JWT_SECRET,{expiresIn:'2h',issuer:'growtechaxon-api',audience:'growtechaxon-admin'});res.json({success:true,message:'Login successful.',token})}catch(e){res.status(500).json({success:false,message:'Login server error.'})}});
app.post('/api/leads',leadLimiter,async(req,res)=>{try{const d={name:text(req.body.name,80),business:text(req.body.business,120),email:text(req.body.email,120).toLowerCase(),phone:text(req.body.phone,20),city:text(req.body.city,80),service:text(req.body.service,100),budget:text(req.body.budget,80),message:text(req.body.message,3000)};if(!d.name||!validEmail(d.email)||!d.phone||!d.message)return res.status(400).json({success:false,message:'Name, valid email, phone and message are required.'});if(!/^[+\d\s().-]{7,20}$/.test(d.phone))return res.status(400).json({success:false,message:'Please provide a valid phone number.'});const lead=await Lead.create(d);res.status(201).json({success:true,message:'Enquiry received successfully.',lead:{id:lead._id}})}catch(e){console.error('[lead]',e.message);res.status(500).json({success:false,message:'Unable to save enquiry right now.'})}});
app.get('/api/leads',auth,async(r,s)=>{try{s.json({success:true,leads:await Lead.find().sort({createdAt:-1}).lean()})}catch{s.status(500).json({success:false,message:'Unable to load leads.'})}});
app.put('/api/leads/:id/status',auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({success:false,message:'Invalid lead id.'});const st=text(req.body.status,20);if(!['New','Contacted','Converted','Closed'].includes(st))return res.status(400).json({success:false,message:'Invalid lead status.'});const lead=await Lead.findByIdAndUpdate(req.params.id,{status:st},{new:true,runValidators:true});if(!lead)return res.status(404).json({success:false,message:'Lead not found.'});res.json({success:true,lead})}catch{res.status(500).json({success:false,message:'Unable to update lead.'})}});
app.delete('/api/leads/:id',auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({success:false,message:'Invalid lead id.'});const lead=await Lead.findByIdAndDelete(req.params.id);if(!lead)return res.status(404).json({success:false,message:'Lead not found.'});res.json({success:true,message:'Lead deleted.'})}catch{res.status(500).json({success:false,message:'Unable to delete lead.'})}});
app.get('/api/team',async(r,s)=>{try{const team=await Team.find({active:true}).sort({isFounder:-1,displayOrder:1,createdAt:1}).lean();s.json({success:true,team})}catch{s.status(500).json({success:false,message:'Unable to load team.'})}});
app.get('/api/admin/team',auth,async(r,s)=>{try{s.json({success:true,team:await Team.find().sort({isFounder:-1,displayOrder:1,createdAt:1}).lean()})}catch{s.status(500).json({success:false,message:'Unable to load team.'})}});
app.post('/api/admin/team',auth,upload.single('photo'),async(req,res)=>{try{const name=text(req.body.name,100),designation=text(req.body.designation,120);if(!name||!designation)return res.status(400).json({success:false,message:'Name and designation are required.'});const isFounder=String(req.body.isFounder)==='true';const d={name,designation,description:text(req.body.description,1000),linkedin:validUrl(req.body.linkedin),isFounder,displayOrder:Number(req.body.displayOrder)||0,active:String(req.body.active)!=='false'};if(req.file){if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({success:false,message:'Image storage is not configured.'});d.photo=(await uploadCloud(req.file.buffer)).secure_url}if(isFounder)await Team.updateMany({},{$set:{isFounder:false}});const team=await Team.create(d);res.status(201).json({success:true,message:'Team member added successfully.',team})}catch(e){console.error('[team]',e.message);res.status(500).json({success:false,message:'Unable to add team member.'})}});
app.put('/api/admin/team/:id',auth,upload.single('photo'),async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({success:false,message:'Invalid team id.'});const old=await Team.findById(req.params.id);if(!old)return res.status(404).json({success:false,message:'Team member not found.'});const isFounder=String(req.body.isFounder)==='true';const d={name:text(req.body.name,100),designation:text(req.body.designation,120),description:text(req.body.description,1000),linkedin:validUrl(req.body.linkedin),isFounder,displayOrder:Number(req.body.displayOrder)||0,active:String(req.body.active)!=='false'};if(!d.name||!d.designation)return res.status(400).json({success:false,message:'Name and designation are required.'});if(req.file){if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({success:false,message:'Image storage is not configured.'});d.photo=(await uploadCloud(req.file.buffer)).secure_url}else d.photo=old.photo||'';if(isFounder)await Team.updateMany({_id:{$ne:req.params.id}},{$set:{isFounder:false}});const team=await Team.findByIdAndUpdate(req.params.id,d,{new:true,runValidators:true});res.json({success:true,message:'Team member updated successfully.',team})}catch(e){console.error('[team-update]',e.message);res.status(500).json({success:false,message:'Unable to update team member.'})}});
app.delete('/api/admin/team/:id',auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({success:false,message:'Invalid team id.'});const team=await Team.findByIdAndDelete(req.params.id);if(!team)return res.status(404).json({success:false,message:'Team member not found.'});res.json({success:true,message:'Team member deleted successfully.'})}catch{res.status(500).json({success:false,message:'Unable to delete team member.'})}});
app.use((e,r,s,n)=>s.status(400).json({success:false,message:e.message||'Bad request.'}));app.use('/api',(r,s)=>s.status(404).json({success:false,message:'API route not found.'}));
(async()=>{if(process.env.MONGODB_URI){try{await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:8000});console.log('✓ MongoDB connected')}catch(e){console.error('✗ MongoDB:',e.message)}}else console.warn('! MONGODB_URI is not configured.');app.listen(PORT,()=>console.log(`GrowtechAxon API running on http://localhost:${PORT}`))})();
